_target_: pytorch_lightning.Trainer

# set `1` to train on GPU, `0` to train on CPU only
gpus: 0

max_steps: 100000
min_steps: 1000

weights_summary: null
progress_bar_refresh_rate: 5
resume_from_checkpoint: null